package com.school.course.course_stage.MybaitsGenerator.Mapper;

import com.school.course.course_stage.MybaitsGenerator.Entity.SchoolClass;
import com.school.course.course_stage.MybaitsGenerator.Entity.SchoolClassExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SchoolClassMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_class
     *
     * @mbg.generated Fri Feb 04 13:59:14 CST 2022
     */
    long countByExample(SchoolClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_class
     *
     * @mbg.generated Fri Feb 04 13:59:14 CST 2022
     */
    int deleteByExample(SchoolClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_class
     *
     * @mbg.generated Fri Feb 04 13:59:14 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_class
     *
     * @mbg.generated Fri Feb 04 13:59:14 CST 2022
     */
    int insert(SchoolClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_class
     *
     * @mbg.generated Fri Feb 04 13:59:14 CST 2022
     */
    int insertSelective(SchoolClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_class
     *
     * @mbg.generated Fri Feb 04 13:59:14 CST 2022
     */
    List<SchoolClass> selectByExample(SchoolClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_class
     *
     * @mbg.generated Fri Feb 04 13:59:14 CST 2022
     */
    SchoolClass selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_class
     *
     * @mbg.generated Fri Feb 04 13:59:14 CST 2022
     */
    int updateByExampleSelective(@Param("record") SchoolClass record, @Param("example") SchoolClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_class
     *
     * @mbg.generated Fri Feb 04 13:59:14 CST 2022
     */
    int updateByExample(@Param("record") SchoolClass record, @Param("example") SchoolClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_class
     *
     * @mbg.generated Fri Feb 04 13:59:14 CST 2022
     */
    int updateByPrimaryKeySelective(SchoolClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_class
     *
     * @mbg.generated Fri Feb 04 13:59:14 CST 2022
     */
    int updateByPrimaryKey(SchoolClass record);
}