package com.school.course.course_stage.MybaitsGenerator.Mapper;

import com.school.course.course_stage.MybaitsGenerator.Entity.SystemMenu;
import com.school.course.course_stage.MybaitsGenerator.Entity.SystemMenuExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface SystemMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_menu
     *
     * @mbg.generated Sat Jan 29 20:47:43 CST 2022
     */
    long countByExample(SystemMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_menu
     *
     * @mbg.generated Sat Jan 29 20:47:43 CST 2022
     */
    int deleteByExample(SystemMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_menu
     *
     * @mbg.generated Sat Jan 29 20:47:43 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_menu
     *
     * @mbg.generated Sat Jan 29 20:47:43 CST 2022
     */
    int insert(SystemMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_menu
     *
     * @mbg.generated Sat Jan 29 20:47:43 CST 2022
     */
    int insertSelective(SystemMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_menu
     *
     * @mbg.generated Sat Jan 29 20:47:43 CST 2022
     */
    List<SystemMenu> selectByExample(SystemMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_menu
     *
     * @mbg.generated Sat Jan 29 20:47:43 CST 2022
     */
    SystemMenu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_menu
     *
     * @mbg.generated Sat Jan 29 20:47:43 CST 2022
     */
    int updateByExampleSelective(@Param("record") SystemMenu record, @Param("example") SystemMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_menu
     *
     * @mbg.generated Sat Jan 29 20:47:43 CST 2022
     */
    int updateByExample(@Param("record") SystemMenu record, @Param("example") SystemMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_menu
     *
     * @mbg.generated Sat Jan 29 20:47:43 CST 2022
     */
    int updateByPrimaryKeySelective(SystemMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_menu
     *
     * @mbg.generated Sat Jan 29 20:47:43 CST 2022
     */
    int updateByPrimaryKey(SystemMenu record);
}