package com.school.course.course_stage.MybaitsGenerator.Mapper;

import com.school.course.course_stage.MybaitsGenerator.Entity.TeachCourse;
import com.school.course.course_stage.MybaitsGenerator.Entity.TeachCourseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TeachCourseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_teach_course
     *
     * @mbg.generated Mon Feb 07 20:02:55 CST 2022
     */
    long countByExample(TeachCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_teach_course
     *
     * @mbg.generated Mon Feb 07 20:02:55 CST 2022
     */
    int deleteByExample(TeachCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_teach_course
     *
     * @mbg.generated Mon Feb 07 20:02:55 CST 2022
     */
    int insert(TeachCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_teach_course
     *
     * @mbg.generated Mon Feb 07 20:02:55 CST 2022
     */
    int insertSelective(TeachCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_teach_course
     *
     * @mbg.generated Mon Feb 07 20:02:55 CST 2022
     */
    List<TeachCourse> selectByExample(TeachCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_teach_course
     *
     * @mbg.generated Mon Feb 07 20:02:55 CST 2022
     */
    int updateByExampleSelective(@Param("record") TeachCourse record, @Param("example") TeachCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_teach_course
     *
     * @mbg.generated Mon Feb 07 20:02:55 CST 2022
     */
    int updateByExample(@Param("record") TeachCourse record, @Param("example") TeachCourseExample example);
}