package com.school.course.course_stage.MybaitsGenerator.Mapper;

import com.school.course.course_stage.MybaitsGenerator.Entity.TypeCourse;
import com.school.course.course_stage.MybaitsGenerator.Entity.TypeCourseExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface TypeCourseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_course
     *
     * @mbg.generated Mon Feb 07 17:09:24 CST 2022
     */
    long countByExample(TypeCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_course
     *
     * @mbg.generated Mon Feb 07 17:09:24 CST 2022
     */
    int deleteByExample(TypeCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_course
     *
     * @mbg.generated Mon Feb 07 17:09:24 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_course
     *
     * @mbg.generated Mon Feb 07 17:09:24 CST 2022
     */
    int insert(TypeCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_course
     *
     * @mbg.generated Mon Feb 07 17:09:24 CST 2022
     */
    int insertSelective(TypeCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_course
     *
     * @mbg.generated Mon Feb 07 17:09:24 CST 2022
     */
    List<TypeCourse> selectByExample(TypeCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_course
     *
     * @mbg.generated Mon Feb 07 17:09:24 CST 2022
     */
    TypeCourse selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_course
     *
     * @mbg.generated Mon Feb 07 17:09:24 CST 2022
     */
    int updateByExampleSelective(@Param("record") TypeCourse record, @Param("example") TypeCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_course
     *
     * @mbg.generated Mon Feb 07 17:09:24 CST 2022
     */
    int updateByExample(@Param("record") TypeCourse record, @Param("example") TypeCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_course
     *
     * @mbg.generated Mon Feb 07 17:09:24 CST 2022
     */
    int updateByPrimaryKeySelective(TypeCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_course
     *
     * @mbg.generated Mon Feb 07 17:09:24 CST 2022
     */
    int updateByPrimaryKey(TypeCourse record);
}