package com.school.course.course_stage.MybaitsGenerator.Mapper;

import com.school.course.course_stage.MybaitsGenerator.Entity.TypeSchool;
import com.school.course.course_stage.MybaitsGenerator.Entity.TypeSchoolExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface TypeSchoolMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_school
     *
     * @mbg.generated Fri Feb 04 21:21:31 CST 2022
     */
    long countByExample(TypeSchoolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_school
     *
     * @mbg.generated Fri Feb 04 21:21:31 CST 2022
     */
    int deleteByExample(TypeSchoolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_school
     *
     * @mbg.generated Fri Feb 04 21:21:31 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_school
     *
     * @mbg.generated Fri Feb 04 21:21:31 CST 2022
     */
    int insert(TypeSchool record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_school
     *
     * @mbg.generated Fri Feb 04 21:21:31 CST 2022
     */
    int insertSelective(TypeSchool record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_school
     *
     * @mbg.generated Fri Feb 04 21:21:31 CST 2022
     */
    List<TypeSchool> selectByExample(TypeSchoolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_school
     *
     * @mbg.generated Fri Feb 04 21:21:31 CST 2022
     */
    TypeSchool selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_school
     *
     * @mbg.generated Fri Feb 04 21:21:31 CST 2022
     */
    int updateByExampleSelective(@Param("record") TypeSchool record, @Param("example") TypeSchoolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_school
     *
     * @mbg.generated Fri Feb 04 21:21:31 CST 2022
     */
    int updateByExample(@Param("record") TypeSchool record, @Param("example") TypeSchoolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_school
     *
     * @mbg.generated Fri Feb 04 21:21:31 CST 2022
     */
    int updateByPrimaryKeySelective(TypeSchool record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_school
     *
     * @mbg.generated Fri Feb 04 21:21:31 CST 2022
     */
    int updateByPrimaryKey(TypeSchool record);
}