package com.school.course.course_stage.MybaitsGenerator.Mapper;

import com.school.course.course_stage.MybaitsGenerator.Entity.TypeCourseClass;
import com.school.course.course_stage.MybaitsGenerator.Entity.TypeCourseClassExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface TypeCourseClassMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_course_class
     *
     * @mbg.generated Mon Feb 07 19:47:10 CST 2022
     */
    long countByExample(TypeCourseClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_course_class
     *
     * @mbg.generated Mon Feb 07 19:47:10 CST 2022
     */
    int deleteByExample(TypeCourseClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_course_class
     *
     * @mbg.generated Mon Feb 07 19:47:10 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_course_class
     *
     * @mbg.generated Mon Feb 07 19:47:10 CST 2022
     */
    int insert(TypeCourseClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_course_class
     *
     * @mbg.generated Mon Feb 07 19:47:10 CST 2022
     */
    int insertSelective(TypeCourseClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_course_class
     *
     * @mbg.generated Mon Feb 07 19:47:10 CST 2022
     */
    List<TypeCourseClass> selectByExample(TypeCourseClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_course_class
     *
     * @mbg.generated Mon Feb 07 19:47:10 CST 2022
     */
    TypeCourseClass selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_course_class
     *
     * @mbg.generated Mon Feb 07 19:47:10 CST 2022
     */
    int updateByExampleSelective(@Param("record") TypeCourseClass record, @Param("example") TypeCourseClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_course_class
     *
     * @mbg.generated Mon Feb 07 19:47:10 CST 2022
     */
    int updateByExample(@Param("record") TypeCourseClass record, @Param("example") TypeCourseClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_course_class
     *
     * @mbg.generated Mon Feb 07 19:47:10 CST 2022
     */
    int updateByPrimaryKeySelective(TypeCourseClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_course_class
     *
     * @mbg.generated Mon Feb 07 19:47:10 CST 2022
     */
    int updateByPrimaryKey(TypeCourseClass record);
}