package com.school.course.course_stage.MybaitsGenerator.Mapper;

import com.school.course.course_stage.MybaitsGenerator.Entity.UserStudent;
import com.school.course.course_stage.MybaitsGenerator.Entity.UserStudentExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface UserStudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_student
     *
     * @mbg.generated Fri Feb 04 13:59:14 CST 2022
     */
    long countByExample(UserStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_student
     *
     * @mbg.generated Fri Feb 04 13:59:14 CST 2022
     */
    int deleteByExample(UserStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_student
     *
     * @mbg.generated Fri Feb 04 13:59:14 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_student
     *
     * @mbg.generated Fri Feb 04 13:59:14 CST 2022
     */
    int insert(UserStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_student
     *
     * @mbg.generated Fri Feb 04 13:59:14 CST 2022
     */
    int insertSelective(UserStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_student
     *
     * @mbg.generated Fri Feb 04 13:59:14 CST 2022
     */
    List<UserStudent> selectByExample(UserStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_student
     *
     * @mbg.generated Fri Feb 04 13:59:14 CST 2022
     */
    UserStudent selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_student
     *
     * @mbg.generated Fri Feb 04 13:59:14 CST 2022
     */
    int updateByExampleSelective(@Param("record") UserStudent record, @Param("example") UserStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_student
     *
     * @mbg.generated Fri Feb 04 13:59:14 CST 2022
     */
    int updateByExample(@Param("record") UserStudent record, @Param("example") UserStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_student
     *
     * @mbg.generated Fri Feb 04 13:59:14 CST 2022
     */
    int updateByPrimaryKeySelective(UserStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_student
     *
     * @mbg.generated Fri Feb 04 13:59:14 CST 2022
     */
    int updateByPrimaryKey(UserStudent record);
}