package com.school.course.course_stage.MybaitsGenerator.Mapper;

import com.school.course.course_stage.MybaitsGenerator.Entity.UserTeacherManage;
import com.school.course.course_stage.MybaitsGenerator.Entity.UserTeacherManageExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface UserTeacherManageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_teacher_manage
     *
     * @mbg.generated Fri Feb 04 13:59:14 CST 2022
     */
    long countByExample(UserTeacherManageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_teacher_manage
     *
     * @mbg.generated Fri Feb 04 13:59:14 CST 2022
     */
    int deleteByExample(UserTeacherManageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_teacher_manage
     *
     * @mbg.generated Fri Feb 04 13:59:14 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_teacher_manage
     *
     * @mbg.generated Fri Feb 04 13:59:14 CST 2022
     */
    int insert(UserTeacherManage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_teacher_manage
     *
     * @mbg.generated Fri Feb 04 13:59:14 CST 2022
     */
    int insertSelective(UserTeacherManage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_teacher_manage
     *
     * @mbg.generated Fri Feb 04 13:59:14 CST 2022
     */
    List<UserTeacherManage> selectByExample(UserTeacherManageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_teacher_manage
     *
     * @mbg.generated Fri Feb 04 13:59:14 CST 2022
     */
    UserTeacherManage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_teacher_manage
     *
     * @mbg.generated Fri Feb 04 13:59:14 CST 2022
     */
    int updateByExampleSelective(@Param("record") UserTeacherManage record, @Param("example") UserTeacherManageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_teacher_manage
     *
     * @mbg.generated Fri Feb 04 13:59:14 CST 2022
     */
    int updateByExample(@Param("record") UserTeacherManage record, @Param("example") UserTeacherManageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_teacher_manage
     *
     * @mbg.generated Fri Feb 04 13:59:14 CST 2022
     */
    int updateByPrimaryKeySelective(UserTeacherManage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_teacher_manage
     *
     * @mbg.generated Fri Feb 04 13:59:14 CST 2022
     */
    int updateByPrimaryKey(UserTeacherManage record);
}