package com.school.course.course_stage.MybaitsGenerator.Mapper;

import com.school.course.course_stage.MybaitsGenerator.Entity.UserTeacherTeache;
import com.school.course.course_stage.MybaitsGenerator.Entity.UserTeacherTeacheExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface UserTeacherTeacheMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_teacher_teache
     *
     * @mbg.generated Fri Feb 04 13:59:14 CST 2022
     */
    long countByExample(UserTeacherTeacheExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_teacher_teache
     *
     * @mbg.generated Fri Feb 04 13:59:14 CST 2022
     */
    int deleteByExample(UserTeacherTeacheExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_teacher_teache
     *
     * @mbg.generated Fri Feb 04 13:59:14 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_teacher_teache
     *
     * @mbg.generated Fri Feb 04 13:59:14 CST 2022
     */
    int insert(UserTeacherTeache record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_teacher_teache
     *
     * @mbg.generated Fri Feb 04 13:59:14 CST 2022
     */
    int insertSelective(UserTeacherTeache record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_teacher_teache
     *
     * @mbg.generated Fri Feb 04 13:59:14 CST 2022
     */
    List<UserTeacherTeache> selectByExample(UserTeacherTeacheExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_teacher_teache
     *
     * @mbg.generated Fri Feb 04 13:59:14 CST 2022
     */
    UserTeacherTeache selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_teacher_teache
     *
     * @mbg.generated Fri Feb 04 13:59:14 CST 2022
     */
    int updateByExampleSelective(@Param("record") UserTeacherTeache record, @Param("example") UserTeacherTeacheExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_teacher_teache
     *
     * @mbg.generated Fri Feb 04 13:59:14 CST 2022
     */
    int updateByExample(@Param("record") UserTeacherTeache record, @Param("example") UserTeacherTeacheExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_teacher_teache
     *
     * @mbg.generated Fri Feb 04 13:59:14 CST 2022
     */
    int updateByPrimaryKeySelective(UserTeacherTeache record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_teacher_teache
     *
     * @mbg.generated Fri Feb 04 13:59:14 CST 2022
     */
    int updateByPrimaryKey(UserTeacherTeache record);
}