server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://150.158.32.183:3306/course_stage
    username: test1
    password: test1

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml