server:
  port: 8080

spring:
  application:
    name: School Course Stage
  datasource:
    url: jdbc:mysql://150.158.32.183:3306/course_stage
    username: test1
    password: test1
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: /static/**

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml