package com.school.course.course_stage.MybaitsGenerator.Entity;

import org.apache.ibatis.annotations.Mapper;

import java.io.Serializable;


@Mapper
public class Course implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.id
     *
     * @mbg.generated Tue Feb 08 20:40:42 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.name
     *
     * @mbg.generated Tue Feb 08 20:40:42 CST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.type_course_id
     *
     * @mbg.generated Tue Feb 08 20:40:42 CST 2022
     */
    private Integer typeCourseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.number_class
     *
     * @mbg.generated Tue Feb 08 20:40:42 CST 2022
     */
    private Integer numberClass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.adapt_level
     *
     * @mbg.generated Tue Feb 08 20:40:42 CST 2022
     */
    private String adaptLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.type_course_class_id
     *
     * @mbg.generated Tue Feb 08 20:40:42 CST 2022
     */
    private Integer typeCourseClassId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.price
     *
     * @mbg.generated Tue Feb 08 20:40:42 CST 2022
     */
    private Float price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.detail
     *
     * @mbg.generated Tue Feb 08 20:40:42 CST 2022
     */
    private String detail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table course
     *
     * @mbg.generated Tue Feb 08 20:40:42 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.id
     *
     * @return the value of course.id
     *
     * @mbg.generated Tue Feb 08 20:40:42 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.id
     *
     * @param id the value for course.id
     *
     * @mbg.generated Tue Feb 08 20:40:42 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.name
     *
     * @return the value of course.name
     *
     * @mbg.generated Tue Feb 08 20:40:42 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.name
     *
     * @param name the value for course.name
     *
     * @mbg.generated Tue Feb 08 20:40:42 CST 2022
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.type_course_id
     *
     * @return the value of course.type_course_id
     *
     * @mbg.generated Tue Feb 08 20:40:42 CST 2022
     */
    public Integer getTypeCourseId() {
        return typeCourseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.type_course_id
     *
     * @param typeCourseId the value for course.type_course_id
     *
     * @mbg.generated Tue Feb 08 20:40:42 CST 2022
     */
    public void setTypeCourseId(Integer typeCourseId) {
        this.typeCourseId = typeCourseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.number_class
     *
     * @return the value of course.number_class
     *
     * @mbg.generated Tue Feb 08 20:40:42 CST 2022
     */
    public Integer getNumberClass() {
        return numberClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.number_class
     *
     * @param numberClass the value for course.number_class
     *
     * @mbg.generated Tue Feb 08 20:40:42 CST 2022
     */
    public void setNumberClass(Integer numberClass) {
        this.numberClass = numberClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.adapt_level
     *
     * @return the value of course.adapt_level
     *
     * @mbg.generated Tue Feb 08 20:40:42 CST 2022
     */
    public String getAdaptLevel() {
        return adaptLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.adapt_level
     *
     * @param adaptLevel the value for course.adapt_level
     *
     * @mbg.generated Tue Feb 08 20:40:42 CST 2022
     */
    public void setAdaptLevel(String adaptLevel) {
        this.adaptLevel = adaptLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.type_course_class_id
     *
     * @return the value of course.type_course_class_id
     *
     * @mbg.generated Tue Feb 08 20:40:42 CST 2022
     */
    public Integer getTypeCourseClassId() {
        return typeCourseClassId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.type_course_class_id
     *
     * @param typeCourseClassId the value for course.type_course_class_id
     *
     * @mbg.generated Tue Feb 08 20:40:42 CST 2022
     */
    public void setTypeCourseClassId(Integer typeCourseClassId) {
        this.typeCourseClassId = typeCourseClassId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.price
     *
     * @return the value of course.price
     *
     * @mbg.generated Tue Feb 08 20:40:42 CST 2022
     */
    public Float getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.price
     *
     * @param price the value for course.price
     *
     * @mbg.generated Tue Feb 08 20:40:42 CST 2022
     */
    public void setPrice(Float price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.detail
     *
     * @return the value of course.detail
     *
     * @mbg.generated Tue Feb 08 20:40:42 CST 2022
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.detail
     *
     * @param detail the value for course.detail
     *
     * @mbg.generated Tue Feb 08 20:40:42 CST 2022
     */
    public void setDetail(String detail) {
        this.detail = detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Tue Feb 08 20:40:42 CST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", typeCourseId=").append(typeCourseId);
        sb.append(", numberClass=").append(numberClass);
        sb.append(", adaptLevel=").append(adaptLevel);
        sb.append(", typeCourseClassId=").append(typeCourseClassId);
        sb.append(", price=").append(price);
        sb.append(", detail=").append(detail);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}