package com.school.course.course_stage.MybaitsGenerator.Entity;

import java.io.Serializable;

public class CourseSchool implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_school.id
     *
     * @mbg.generated Thu Feb 10 22:02:58 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_school.course_name
     *
     * @mbg.generated Thu Feb 10 22:02:58 CST 2022
     */
    private String courseName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_school.course_id
     *
     * @mbg.generated Thu Feb 10 22:02:58 CST 2022
     */
    private Integer courseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_school.school_name
     *
     * @mbg.generated Thu Feb 10 22:02:58 CST 2022
     */
    private String schoolName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_school.school_id
     *
     * @mbg.generated Thu Feb 10 22:02:58 CST 2022
     */
    private Integer schoolId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_school.adapt_time
     *
     * @mbg.generated Thu Feb 10 22:02:58 CST 2022
     */
    private String adaptTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table course_school
     *
     * @mbg.generated Thu Feb 10 22:02:58 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_school.id
     *
     * @return the value of course_school.id
     *
     * @mbg.generated Thu Feb 10 22:02:58 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_school.id
     *
     * @param id the value for course_school.id
     *
     * @mbg.generated Thu Feb 10 22:02:58 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_school.course_name
     *
     * @return the value of course_school.course_name
     *
     * @mbg.generated Thu Feb 10 22:02:58 CST 2022
     */
    public String getCourseName() {
        return courseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_school.course_name
     *
     * @param courseName the value for course_school.course_name
     *
     * @mbg.generated Thu Feb 10 22:02:58 CST 2022
     */
    public void setCourseName(String courseName) {
        this.courseName = courseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_school.course_id
     *
     * @return the value of course_school.course_id
     *
     * @mbg.generated Thu Feb 10 22:02:58 CST 2022
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_school.course_id
     *
     * @param courseId the value for course_school.course_id
     *
     * @mbg.generated Thu Feb 10 22:02:58 CST 2022
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_school.school_name
     *
     * @return the value of course_school.school_name
     *
     * @mbg.generated Thu Feb 10 22:02:58 CST 2022
     */
    public String getSchoolName() {
        return schoolName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_school.school_name
     *
     * @param schoolName the value for course_school.school_name
     *
     * @mbg.generated Thu Feb 10 22:02:58 CST 2022
     */
    public void setSchoolName(String schoolName) {
        this.schoolName = schoolName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_school.school_id
     *
     * @return the value of course_school.school_id
     *
     * @mbg.generated Thu Feb 10 22:02:58 CST 2022
     */
    public Integer getSchoolId() {
        return schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_school.school_id
     *
     * @param schoolId the value for course_school.school_id
     *
     * @mbg.generated Thu Feb 10 22:02:58 CST 2022
     */
    public void setSchoolId(Integer schoolId) {
        this.schoolId = schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_school.adapt_time
     *
     * @return the value of course_school.adapt_time
     *
     * @mbg.generated Thu Feb 10 22:02:58 CST 2022
     */
    public String getAdaptTime() {
        return adaptTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_school.adapt_time
     *
     * @param adaptTime the value for course_school.adapt_time
     *
     * @mbg.generated Thu Feb 10 22:02:58 CST 2022
     */
    public void setAdaptTime(String adaptTime) {
        this.adaptTime = adaptTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_school
     *
     * @mbg.generated Thu Feb 10 22:02:58 CST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", courseName=").append(courseName);
        sb.append(", courseId=").append(courseId);
        sb.append(", schoolName=").append(schoolName);
        sb.append(", schoolId=").append(schoolId);
        sb.append(", adaptTime=").append(adaptTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}