package com.school.course.course_stage.MybaitsGenerator.Entity;

import java.util.ArrayList;
import java.util.List;

public class CourseExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table course
     *
     * @mbg.generated Tue Feb 08 20:40:42 CST 2022
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table course
     *
     * @mbg.generated Tue Feb 08 20:40:42 CST 2022
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table course
     *
     * @mbg.generated Tue Feb 08 20:40:42 CST 2022
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Tue Feb 08 20:40:42 CST 2022
     */
    public CourseExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Tue Feb 08 20:40:42 CST 2022
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Tue Feb 08 20:40:42 CST 2022
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Tue Feb 08 20:40:42 CST 2022
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Tue Feb 08 20:40:42 CST 2022
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Tue Feb 08 20:40:42 CST 2022
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Tue Feb 08 20:40:42 CST 2022
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Tue Feb 08 20:40:42 CST 2022
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Tue Feb 08 20:40:42 CST 2022
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Tue Feb 08 20:40:42 CST 2022
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Tue Feb 08 20:40:42 CST 2022
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table course
     *
     * @mbg.generated Tue Feb 08 20:40:42 CST 2022
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andTypeCourseIdIsNull() {
            addCriterion("type_course_id is null");
            return (Criteria) this;
        }

        public Criteria andTypeCourseIdIsNotNull() {
            addCriterion("type_course_id is not null");
            return (Criteria) this;
        }

        public Criteria andTypeCourseIdEqualTo(Integer value) {
            addCriterion("type_course_id =", value, "typeCourseId");
            return (Criteria) this;
        }

        public Criteria andTypeCourseIdNotEqualTo(Integer value) {
            addCriterion("type_course_id <>", value, "typeCourseId");
            return (Criteria) this;
        }

        public Criteria andTypeCourseIdGreaterThan(Integer value) {
            addCriterion("type_course_id >", value, "typeCourseId");
            return (Criteria) this;
        }

        public Criteria andTypeCourseIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("type_course_id >=", value, "typeCourseId");
            return (Criteria) this;
        }

        public Criteria andTypeCourseIdLessThan(Integer value) {
            addCriterion("type_course_id <", value, "typeCourseId");
            return (Criteria) this;
        }

        public Criteria andTypeCourseIdLessThanOrEqualTo(Integer value) {
            addCriterion("type_course_id <=", value, "typeCourseId");
            return (Criteria) this;
        }

        public Criteria andTypeCourseIdIn(List<Integer> values) {
            addCriterion("type_course_id in", values, "typeCourseId");
            return (Criteria) this;
        }

        public Criteria andTypeCourseIdNotIn(List<Integer> values) {
            addCriterion("type_course_id not in", values, "typeCourseId");
            return (Criteria) this;
        }

        public Criteria andTypeCourseIdBetween(Integer value1, Integer value2) {
            addCriterion("type_course_id between", value1, value2, "typeCourseId");
            return (Criteria) this;
        }

        public Criteria andTypeCourseIdNotBetween(Integer value1, Integer value2) {
            addCriterion("type_course_id not between", value1, value2, "typeCourseId");
            return (Criteria) this;
        }

        public Criteria andNumberClassIsNull() {
            addCriterion("number_class is null");
            return (Criteria) this;
        }

        public Criteria andNumberClassIsNotNull() {
            addCriterion("number_class is not null");
            return (Criteria) this;
        }

        public Criteria andNumberClassEqualTo(Integer value) {
            addCriterion("number_class =", value, "numberClass");
            return (Criteria) this;
        }

        public Criteria andNumberClassNotEqualTo(Integer value) {
            addCriterion("number_class <>", value, "numberClass");
            return (Criteria) this;
        }

        public Criteria andNumberClassGreaterThan(Integer value) {
            addCriterion("number_class >", value, "numberClass");
            return (Criteria) this;
        }

        public Criteria andNumberClassGreaterThanOrEqualTo(Integer value) {
            addCriterion("number_class >=", value, "numberClass");
            return (Criteria) this;
        }

        public Criteria andNumberClassLessThan(Integer value) {
            addCriterion("number_class <", value, "numberClass");
            return (Criteria) this;
        }

        public Criteria andNumberClassLessThanOrEqualTo(Integer value) {
            addCriterion("number_class <=", value, "numberClass");
            return (Criteria) this;
        }

        public Criteria andNumberClassIn(List<Integer> values) {
            addCriterion("number_class in", values, "numberClass");
            return (Criteria) this;
        }

        public Criteria andNumberClassNotIn(List<Integer> values) {
            addCriterion("number_class not in", values, "numberClass");
            return (Criteria) this;
        }

        public Criteria andNumberClassBetween(Integer value1, Integer value2) {
            addCriterion("number_class between", value1, value2, "numberClass");
            return (Criteria) this;
        }

        public Criteria andNumberClassNotBetween(Integer value1, Integer value2) {
            addCriterion("number_class not between", value1, value2, "numberClass");
            return (Criteria) this;
        }

        public Criteria andAdaptLevelIsNull() {
            addCriterion("adapt_level is null");
            return (Criteria) this;
        }

        public Criteria andAdaptLevelIsNotNull() {
            addCriterion("adapt_level is not null");
            return (Criteria) this;
        }

        public Criteria andAdaptLevelEqualTo(String value) {
            addCriterion("adapt_level =", value, "adaptLevel");
            return (Criteria) this;
        }

        public Criteria andAdaptLevelNotEqualTo(String value) {
            addCriterion("adapt_level <>", value, "adaptLevel");
            return (Criteria) this;
        }

        public Criteria andAdaptLevelGreaterThan(String value) {
            addCriterion("adapt_level >", value, "adaptLevel");
            return (Criteria) this;
        }

        public Criteria andAdaptLevelGreaterThanOrEqualTo(String value) {
            addCriterion("adapt_level >=", value, "adaptLevel");
            return (Criteria) this;
        }

        public Criteria andAdaptLevelLessThan(String value) {
            addCriterion("adapt_level <", value, "adaptLevel");
            return (Criteria) this;
        }

        public Criteria andAdaptLevelLessThanOrEqualTo(String value) {
            addCriterion("adapt_level <=", value, "adaptLevel");
            return (Criteria) this;
        }

        public Criteria andAdaptLevelLike(String value) {
            addCriterion("adapt_level like", value, "adaptLevel");
            return (Criteria) this;
        }

        public Criteria andAdaptLevelNotLike(String value) {
            addCriterion("adapt_level not like", value, "adaptLevel");
            return (Criteria) this;
        }

        public Criteria andAdaptLevelIn(List<String> values) {
            addCriterion("adapt_level in", values, "adaptLevel");
            return (Criteria) this;
        }

        public Criteria andAdaptLevelNotIn(List<String> values) {
            addCriterion("adapt_level not in", values, "adaptLevel");
            return (Criteria) this;
        }

        public Criteria andAdaptLevelBetween(String value1, String value2) {
            addCriterion("adapt_level between", value1, value2, "adaptLevel");
            return (Criteria) this;
        }

        public Criteria andAdaptLevelNotBetween(String value1, String value2) {
            addCriterion("adapt_level not between", value1, value2, "adaptLevel");
            return (Criteria) this;
        }

        public Criteria andTypeCourseClassIdIsNull() {
            addCriterion("type_course_class_id is null");
            return (Criteria) this;
        }

        public Criteria andTypeCourseClassIdIsNotNull() {
            addCriterion("type_course_class_id is not null");
            return (Criteria) this;
        }

        public Criteria andTypeCourseClassIdEqualTo(Integer value) {
            addCriterion("type_course_class_id =", value, "typeCourseClassId");
            return (Criteria) this;
        }

        public Criteria andTypeCourseClassIdNotEqualTo(Integer value) {
            addCriterion("type_course_class_id <>", value, "typeCourseClassId");
            return (Criteria) this;
        }

        public Criteria andTypeCourseClassIdGreaterThan(Integer value) {
            addCriterion("type_course_class_id >", value, "typeCourseClassId");
            return (Criteria) this;
        }

        public Criteria andTypeCourseClassIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("type_course_class_id >=", value, "typeCourseClassId");
            return (Criteria) this;
        }

        public Criteria andTypeCourseClassIdLessThan(Integer value) {
            addCriterion("type_course_class_id <", value, "typeCourseClassId");
            return (Criteria) this;
        }

        public Criteria andTypeCourseClassIdLessThanOrEqualTo(Integer value) {
            addCriterion("type_course_class_id <=", value, "typeCourseClassId");
            return (Criteria) this;
        }

        public Criteria andTypeCourseClassIdIn(List<Integer> values) {
            addCriterion("type_course_class_id in", values, "typeCourseClassId");
            return (Criteria) this;
        }

        public Criteria andTypeCourseClassIdNotIn(List<Integer> values) {
            addCriterion("type_course_class_id not in", values, "typeCourseClassId");
            return (Criteria) this;
        }

        public Criteria andTypeCourseClassIdBetween(Integer value1, Integer value2) {
            addCriterion("type_course_class_id between", value1, value2, "typeCourseClassId");
            return (Criteria) this;
        }

        public Criteria andTypeCourseClassIdNotBetween(Integer value1, Integer value2) {
            addCriterion("type_course_class_id not between", value1, value2, "typeCourseClassId");
            return (Criteria) this;
        }

        public Criteria andPriceIsNull() {
            addCriterion("price is null");
            return (Criteria) this;
        }

        public Criteria andPriceIsNotNull() {
            addCriterion("price is not null");
            return (Criteria) this;
        }

        public Criteria andPriceEqualTo(Float value) {
            addCriterion("price =", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotEqualTo(Float value) {
            addCriterion("price <>", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThan(Float value) {
            addCriterion("price >", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThanOrEqualTo(Float value) {
            addCriterion("price >=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThan(Float value) {
            addCriterion("price <", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThanOrEqualTo(Float value) {
            addCriterion("price <=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceIn(List<Float> values) {
            addCriterion("price in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotIn(List<Float> values) {
            addCriterion("price not in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceBetween(Float value1, Float value2) {
            addCriterion("price between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotBetween(Float value1, Float value2) {
            addCriterion("price not between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andDetailIsNull() {
            addCriterion("detail is null");
            return (Criteria) this;
        }

        public Criteria andDetailIsNotNull() {
            addCriterion("detail is not null");
            return (Criteria) this;
        }

        public Criteria andDetailEqualTo(String value) {
            addCriterion("detail =", value, "detail");
            return (Criteria) this;
        }

        public Criteria andDetailNotEqualTo(String value) {
            addCriterion("detail <>", value, "detail");
            return (Criteria) this;
        }

        public Criteria andDetailGreaterThan(String value) {
            addCriterion("detail >", value, "detail");
            return (Criteria) this;
        }

        public Criteria andDetailGreaterThanOrEqualTo(String value) {
            addCriterion("detail >=", value, "detail");
            return (Criteria) this;
        }

        public Criteria andDetailLessThan(String value) {
            addCriterion("detail <", value, "detail");
            return (Criteria) this;
        }

        public Criteria andDetailLessThanOrEqualTo(String value) {
            addCriterion("detail <=", value, "detail");
            return (Criteria) this;
        }

        public Criteria andDetailLike(String value) {
            addCriterion("detail like", value, "detail");
            return (Criteria) this;
        }

        public Criteria andDetailNotLike(String value) {
            addCriterion("detail not like", value, "detail");
            return (Criteria) this;
        }

        public Criteria andDetailIn(List<String> values) {
            addCriterion("detail in", values, "detail");
            return (Criteria) this;
        }

        public Criteria andDetailNotIn(List<String> values) {
            addCriterion("detail not in", values, "detail");
            return (Criteria) this;
        }

        public Criteria andDetailBetween(String value1, String value2) {
            addCriterion("detail between", value1, value2, "detail");
            return (Criteria) this;
        }

        public Criteria andDetailNotBetween(String value1, String value2) {
            addCriterion("detail not between", value1, value2, "detail");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table course
     *
     * @mbg.generated do_not_delete_during_merge Tue Feb 08 20:40:42 CST 2022
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table course
     *
     * @mbg.generated Tue Feb 08 20:40:42 CST 2022
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}