package com.school.course.course_stage.MybaitsGenerator.Entity;

import java.io.Serializable;
import java.util.Date;

public class SystemMenu implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_menu.id
     *
     * @mbg.generated Sat Jan 29 20:47:43 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_menu.pid
     *
     * @mbg.generated Sat Jan 29 20:47:43 CST 2022
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_menu.title
     *
     * @mbg.generated Sat Jan 29 20:47:43 CST 2022
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_menu.icon
     *
     * @mbg.generated Sat Jan 29 20:47:43 CST 2022
     */
    private String icon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_menu.href
     *
     * @mbg.generated Sat Jan 29 20:47:43 CST 2022
     */
    private String href;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_menu.target
     *
     * @mbg.generated Sat Jan 29 20:47:43 CST 2022
     */
    private String target;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_menu.sort
     *
     * @mbg.generated Sat Jan 29 20:47:43 CST 2022
     */
    private Integer sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_menu.status
     *
     * @mbg.generated Sat Jan 29 20:47:43 CST 2022
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_menu.remark
     *
     * @mbg.generated Sat Jan 29 20:47:43 CST 2022
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_menu.create_at
     *
     * @mbg.generated Sat Jan 29 20:47:43 CST 2022
     */
    private Date createAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_menu.update_at
     *
     * @mbg.generated Sat Jan 29 20:47:43 CST 2022
     */
    private Date updateAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_menu.delete_at
     *
     * @mbg.generated Sat Jan 29 20:47:43 CST 2022
     */
    private Date deleteAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table system_menu
     *
     * @mbg.generated Sat Jan 29 20:47:43 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_menu.id
     *
     * @return the value of system_menu.id
     *
     * @mbg.generated Sat Jan 29 20:47:43 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_menu.id
     *
     * @param id the value for system_menu.id
     *
     * @mbg.generated Sat Jan 29 20:47:43 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_menu.pid
     *
     * @return the value of system_menu.pid
     *
     * @mbg.generated Sat Jan 29 20:47:43 CST 2022
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_menu.pid
     *
     * @param pid the value for system_menu.pid
     *
     * @mbg.generated Sat Jan 29 20:47:43 CST 2022
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_menu.title
     *
     * @return the value of system_menu.title
     *
     * @mbg.generated Sat Jan 29 20:47:43 CST 2022
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_menu.title
     *
     * @param title the value for system_menu.title
     *
     * @mbg.generated Sat Jan 29 20:47:43 CST 2022
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_menu.icon
     *
     * @return the value of system_menu.icon
     *
     * @mbg.generated Sat Jan 29 20:47:43 CST 2022
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_menu.icon
     *
     * @param icon the value for system_menu.icon
     *
     * @mbg.generated Sat Jan 29 20:47:43 CST 2022
     */
    public void setIcon(String icon) {
        this.icon = icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_menu.href
     *
     * @return the value of system_menu.href
     *
     * @mbg.generated Sat Jan 29 20:47:43 CST 2022
     */
    public String getHref() {
        return href;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_menu.href
     *
     * @param href the value for system_menu.href
     *
     * @mbg.generated Sat Jan 29 20:47:43 CST 2022
     */
    public void setHref(String href) {
        this.href = href;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_menu.target
     *
     * @return the value of system_menu.target
     *
     * @mbg.generated Sat Jan 29 20:47:43 CST 2022
     */
    public String getTarget() {
        return target;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_menu.target
     *
     * @param target the value for system_menu.target
     *
     * @mbg.generated Sat Jan 29 20:47:43 CST 2022
     */
    public void setTarget(String target) {
        this.target = target;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_menu.sort
     *
     * @return the value of system_menu.sort
     *
     * @mbg.generated Sat Jan 29 20:47:43 CST 2022
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_menu.sort
     *
     * @param sort the value for system_menu.sort
     *
     * @mbg.generated Sat Jan 29 20:47:43 CST 2022
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_menu.status
     *
     * @return the value of system_menu.status
     *
     * @mbg.generated Sat Jan 29 20:47:43 CST 2022
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_menu.status
     *
     * @param status the value for system_menu.status
     *
     * @mbg.generated Sat Jan 29 20:47:43 CST 2022
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_menu.remark
     *
     * @return the value of system_menu.remark
     *
     * @mbg.generated Sat Jan 29 20:47:43 CST 2022
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_menu.remark
     *
     * @param remark the value for system_menu.remark
     *
     * @mbg.generated Sat Jan 29 20:47:43 CST 2022
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_menu.create_at
     *
     * @return the value of system_menu.create_at
     *
     * @mbg.generated Sat Jan 29 20:47:43 CST 2022
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_menu.create_at
     *
     * @param createAt the value for system_menu.create_at
     *
     * @mbg.generated Sat Jan 29 20:47:43 CST 2022
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_menu.update_at
     *
     * @return the value of system_menu.update_at
     *
     * @mbg.generated Sat Jan 29 20:47:43 CST 2022
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_menu.update_at
     *
     * @param updateAt the value for system_menu.update_at
     *
     * @mbg.generated Sat Jan 29 20:47:43 CST 2022
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_menu.delete_at
     *
     * @return the value of system_menu.delete_at
     *
     * @mbg.generated Sat Jan 29 20:47:43 CST 2022
     */
    public Date getDeleteAt() {
        return deleteAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_menu.delete_at
     *
     * @param deleteAt the value for system_menu.delete_at
     *
     * @mbg.generated Sat Jan 29 20:47:43 CST 2022
     */
    public void setDeleteAt(Date deleteAt) {
        this.deleteAt = deleteAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_menu
     *
     * @mbg.generated Sat Jan 29 20:47:43 CST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", pid=").append(pid);
        sb.append(", title=").append(title);
        sb.append(", icon=").append(icon);
        sb.append(", href=").append(href);
        sb.append(", target=").append(target);
        sb.append(", sort=").append(sort);
        sb.append(", status=").append(status);
        sb.append(", remark=").append(remark);
        sb.append(", createAt=").append(createAt);
        sb.append(", updateAt=").append(updateAt);
        sb.append(", deleteAt=").append(deleteAt);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}