package com.school.course.course_stage.MybaitsGenerator.Entity;

import java.io.Serializable;

public class TeachCourse implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_teach_course.teacher_name
     *
     * @mbg.generated Mon Feb 07 20:02:55 CST 2022
     */
    private String teacherName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_teach_course.course_time
     *
     * @mbg.generated Mon Feb 07 20:02:55 CST 2022
     */
    private String courseTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_teach_course.class_grade
     *
     * @mbg.generated Mon Feb 07 20:02:55 CST 2022
     */
    private String classGrade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_teach_course.course_name
     *
     * @mbg.generated Mon Feb 07 20:02:55 CST 2022
     */
    private String courseName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_teach_course.id
     *
     * @mbg.generated Mon Feb 07 20:02:55 CST 2022
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table teacher_teach_course
     *
     * @mbg.generated Mon Feb 07 20:02:55 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_teach_course.teacher_name
     *
     * @return the value of teacher_teach_course.teacher_name
     *
     * @mbg.generated Mon Feb 07 20:02:55 CST 2022
     */
    public String getTeacherName() {
        return teacherName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_teach_course.teacher_name
     *
     * @param teacherName the value for teacher_teach_course.teacher_name
     *
     * @mbg.generated Mon Feb 07 20:02:55 CST 2022
     */
    public void setTeacherName(String teacherName) {
        this.teacherName = teacherName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_teach_course.course_time
     *
     * @return the value of teacher_teach_course.course_time
     *
     * @mbg.generated Mon Feb 07 20:02:55 CST 2022
     */
    public String getCourseTime() {
        return courseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_teach_course.course_time
     *
     * @param courseTime the value for teacher_teach_course.course_time
     *
     * @mbg.generated Mon Feb 07 20:02:55 CST 2022
     */
    public void setCourseTime(String courseTime) {
        this.courseTime = courseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_teach_course.class_grade
     *
     * @return the value of teacher_teach_course.class_grade
     *
     * @mbg.generated Mon Feb 07 20:02:55 CST 2022
     */
    public String getClassGrade() {
        return classGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_teach_course.class_grade
     *
     * @param classGrade the value for teacher_teach_course.class_grade
     *
     * @mbg.generated Mon Feb 07 20:02:55 CST 2022
     */
    public void setClassGrade(String classGrade) {
        this.classGrade = classGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_teach_course.course_name
     *
     * @return the value of teacher_teach_course.course_name
     *
     * @mbg.generated Mon Feb 07 20:02:55 CST 2022
     */
    public String getCourseName() {
        return courseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_teach_course.course_name
     *
     * @param courseName the value for teacher_teach_course.course_name
     *
     * @mbg.generated Mon Feb 07 20:02:55 CST 2022
     */
    public void setCourseName(String courseName) {
        this.courseName = courseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_teach_course.id
     *
     * @return the value of teacher_teach_course.id
     *
     * @mbg.generated Mon Feb 07 20:02:55 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_teach_course.id
     *
     * @param id the value for teacher_teach_course.id
     *
     * @mbg.generated Mon Feb 07 20:02:55 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_teach_course
     *
     * @mbg.generated Mon Feb 07 20:02:55 CST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", teacherName=").append(teacherName);
        sb.append(", courseTime=").append(courseTime);
        sb.append(", classGrade=").append(classGrade);
        sb.append(", courseName=").append(courseName);
        sb.append(", id=").append(id);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}