package com.school.course.course_stage.MybaitsGenerator.Entity;

import java.io.Serializable;

public class TypeSchool implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column type_school.id
     *
     * @mbg.generated Fri Feb 04 13:59:14 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column type_school.name
     *
     * @mbg.generated Fri Feb 04 13:59:14 CST 2022
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table type_school
     *
     * @mbg.generated Fri Feb 04 13:59:14 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column type_school.id
     *
     * @return the value of type_school.id
     *
     * @mbg.generated Fri Feb 04 13:59:14 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column type_school.id
     *
     * @param id the value for type_school.id
     *
     * @mbg.generated Fri Feb 04 13:59:14 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column type_school.name
     *
     * @return the value of type_school.name
     *
     * @mbg.generated Fri Feb 04 13:59:14 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column type_school.name
     *
     * @param name the value for type_school.name
     *
     * @mbg.generated Fri Feb 04 13:59:14 CST 2022
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_school
     *
     * @mbg.generated Fri Feb 04 13:59:14 CST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}