package com.school.course.course_stage.MybaitsGenerator.Entity;

import java.io.Serializable;
import java.util.Date;

public class UserTeacherTeache implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_teacher_teache.id
     *
     * @mbg.generated Thu Feb 10 11:17:18 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_teacher_teache.name
     *
     * @mbg.generated Thu Feb 10 11:17:18 CST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_teacher_teache.account
     *
     * @mbg.generated Thu Feb 10 11:17:18 CST 2022
     */
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_teacher_teache.password
     *
     * @mbg.generated Thu Feb 10 11:17:18 CST 2022
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_teacher_teache.role
     *
     * @mbg.generated Thu Feb 10 11:17:18 CST 2022
     */
    private String role;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_teacher_teache.phone
     *
     * @mbg.generated Thu Feb 10 11:17:18 CST 2022
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_teacher_teache.image
     *
     * @mbg.generated Thu Feb 10 11:17:18 CST 2022
     */
    private String image;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_teacher_teache.status
     *
     * @mbg.generated Thu Feb 10 11:17:18 CST 2022
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_teacher_teache.token
     *
     * @mbg.generated Thu Feb 10 11:17:18 CST 2022
     */
    private String token;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_teacher_teache.remark
     *
     * @mbg.generated Thu Feb 10 11:17:18 CST 2022
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_teacher_teache.create_at
     *
     * @mbg.generated Thu Feb 10 11:17:18 CST 2022
     */
    private Date createAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_teacher_teache.update_at
     *
     * @mbg.generated Thu Feb 10 11:17:18 CST 2022
     */
    private Date updateAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_teacher_teache.delete_at
     *
     * @mbg.generated Thu Feb 10 11:17:18 CST 2022
     */
    private Date deleteAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_teacher_teache.school_id
     *
     * @mbg.generated Thu Feb 10 11:17:18 CST 2022
     */
    private Integer schoolId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_teacher_teache
     *
     * @mbg.generated Thu Feb 10 11:17:18 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_teacher_teache.id
     *
     * @return the value of user_teacher_teache.id
     *
     * @mbg.generated Thu Feb 10 11:17:18 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_teacher_teache.id
     *
     * @param id the value for user_teacher_teache.id
     *
     * @mbg.generated Thu Feb 10 11:17:18 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_teacher_teache.name
     *
     * @return the value of user_teacher_teache.name
     *
     * @mbg.generated Thu Feb 10 11:17:18 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_teacher_teache.name
     *
     * @param name the value for user_teacher_teache.name
     *
     * @mbg.generated Thu Feb 10 11:17:18 CST 2022
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_teacher_teache.account
     *
     * @return the value of user_teacher_teache.account
     *
     * @mbg.generated Thu Feb 10 11:17:18 CST 2022
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_teacher_teache.account
     *
     * @param account the value for user_teacher_teache.account
     *
     * @mbg.generated Thu Feb 10 11:17:18 CST 2022
     */
    public void setAccount(String account) {
        this.account = account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_teacher_teache.password
     *
     * @return the value of user_teacher_teache.password
     *
     * @mbg.generated Thu Feb 10 11:17:18 CST 2022
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_teacher_teache.password
     *
     * @param password the value for user_teacher_teache.password
     *
     * @mbg.generated Thu Feb 10 11:17:18 CST 2022
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_teacher_teache.role
     *
     * @return the value of user_teacher_teache.role
     *
     * @mbg.generated Thu Feb 10 11:17:18 CST 2022
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_teacher_teache.role
     *
     * @param role the value for user_teacher_teache.role
     *
     * @mbg.generated Thu Feb 10 11:17:18 CST 2022
     */
    public void setRole(String role) {
        this.role = role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_teacher_teache.phone
     *
     * @return the value of user_teacher_teache.phone
     *
     * @mbg.generated Thu Feb 10 11:17:18 CST 2022
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_teacher_teache.phone
     *
     * @param phone the value for user_teacher_teache.phone
     *
     * @mbg.generated Thu Feb 10 11:17:18 CST 2022
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_teacher_teache.image
     *
     * @return the value of user_teacher_teache.image
     *
     * @mbg.generated Thu Feb 10 11:17:18 CST 2022
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_teacher_teache.image
     *
     * @param image the value for user_teacher_teache.image
     *
     * @mbg.generated Thu Feb 10 11:17:18 CST 2022
     */
    public void setImage(String image) {
        this.image = image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_teacher_teache.status
     *
     * @return the value of user_teacher_teache.status
     *
     * @mbg.generated Thu Feb 10 11:17:18 CST 2022
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_teacher_teache.status
     *
     * @param status the value for user_teacher_teache.status
     *
     * @mbg.generated Thu Feb 10 11:17:18 CST 2022
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_teacher_teache.token
     *
     * @return the value of user_teacher_teache.token
     *
     * @mbg.generated Thu Feb 10 11:17:18 CST 2022
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_teacher_teache.token
     *
     * @param token the value for user_teacher_teache.token
     *
     * @mbg.generated Thu Feb 10 11:17:18 CST 2022
     */
    public void setToken(String token) {
        this.token = token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_teacher_teache.remark
     *
     * @return the value of user_teacher_teache.remark
     *
     * @mbg.generated Thu Feb 10 11:17:18 CST 2022
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_teacher_teache.remark
     *
     * @param remark the value for user_teacher_teache.remark
     *
     * @mbg.generated Thu Feb 10 11:17:18 CST 2022
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_teacher_teache.create_at
     *
     * @return the value of user_teacher_teache.create_at
     *
     * @mbg.generated Thu Feb 10 11:17:18 CST 2022
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_teacher_teache.create_at
     *
     * @param createAt the value for user_teacher_teache.create_at
     *
     * @mbg.generated Thu Feb 10 11:17:18 CST 2022
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_teacher_teache.update_at
     *
     * @return the value of user_teacher_teache.update_at
     *
     * @mbg.generated Thu Feb 10 11:17:18 CST 2022
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_teacher_teache.update_at
     *
     * @param updateAt the value for user_teacher_teache.update_at
     *
     * @mbg.generated Thu Feb 10 11:17:18 CST 2022
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_teacher_teache.delete_at
     *
     * @return the value of user_teacher_teache.delete_at
     *
     * @mbg.generated Thu Feb 10 11:17:18 CST 2022
     */
    public Date getDeleteAt() {
        return deleteAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_teacher_teache.delete_at
     *
     * @param deleteAt the value for user_teacher_teache.delete_at
     *
     * @mbg.generated Thu Feb 10 11:17:18 CST 2022
     */
    public void setDeleteAt(Date deleteAt) {
        this.deleteAt = deleteAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_teacher_teache.school_id
     *
     * @return the value of user_teacher_teache.school_id
     *
     * @mbg.generated Thu Feb 10 11:17:18 CST 2022
     */
    public Integer getSchoolId() {
        return schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_teacher_teache.school_id
     *
     * @param schoolId the value for user_teacher_teache.school_id
     *
     * @mbg.generated Thu Feb 10 11:17:18 CST 2022
     */
    public void setSchoolId(Integer schoolId) {
        this.schoolId = schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_teacher_teache
     *
     * @mbg.generated Thu Feb 10 11:17:18 CST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", account=").append(account);
        sb.append(", password=").append(password);
        sb.append(", role=").append(role);
        sb.append(", phone=").append(phone);
        sb.append(", image=").append(image);
        sb.append(", status=").append(status);
        sb.append(", token=").append(token);
        sb.append(", remark=").append(remark);
        sb.append(", createAt=").append(createAt);
        sb.append(", updateAt=").append(updateAt);
        sb.append(", deleteAt=").append(deleteAt);
        sb.append(", schoolId=").append(schoolId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}